services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: tiktok
      POSTGRES_PASSWORD: tiktok
      POSTGRES_DB: tiktok
    ports: ["5432:5432"]

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports: ["2181:2181"]

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on: [zookeeper]
    ports: ["9092:9092"]

  airflow:
    image: apache/airflow:2.9.1
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOGGING_LEVEL: INFO
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://tiktok:tiktok@db:5432/tiktok
      _PIP_ADDITIONAL_REQUIREMENTS: playwright-stealth aiokafka pydantic sqlalchemy psycopg2-binary pandas python-dotenv execjs
    volumes:
      - ./airflow_dags:/opt/airflow/dags
      - ./tiktok_scraper:/opt/airflow/tiktok_scraper
      - ./etl:/opt/airflow/etl
    ports: ["8080:8080"]
    depends_on: [db, kafka]
    command: bash -c "airflow db upgrade && airflow users create --username admin --firstname a --lastname b --role Admin --email admin@example.com --password admin && airflow webserver & airflow scheduler"

  scraper:
    build: .
    env_file: .env.demo
    environment:
      POSTGRES_DSN: postgresql://tiktok:tiktok@db:5432/tiktok
      KAFKA_BOOTSTRAP: kafka:9092
      PROXY_POOL: ""  # put proxies here
      #LOG_LEVEL: INFO
    logging:
      driver: json-file        # default driver, but we tune it
      options:
        max-size: "10m"        # rotate after 10 MB
        max-file: "5" 
    depends_on: [kafka, db]
  
  db-init:
    image: python:3.11-slim
    command: python /scripts/init_db.py
    volumes:
      - ./scripts:/scripts
    environment:
      DB_URL: postgresql+psycopg://scraper:password@db/scraper
    depends_on: [db]